steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/kubernetesassignment-428922/kubernetes-assignment-repo/container2:latest', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/kubernetesassignment-428922/kubernetes-assignment-repo/container2:latest']
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - apply
  - -f
  - ./deployment-service.yaml
  - -f
  - ./pvc.yaml
  - --namespace=default
  env:
  - 'CLOUDSDK_CONTAINER_CLUSTER=primary-cluster'
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1'
images:
- 'us-central1-docker.pkg.dev/kubernetesassignment-428922/kubernetes-assignment-repo/container2:latest'
options:
  logging: CLOUD_LOGGING_ONLY
