steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/kubernetesassignment-428915/kubernetes-assignment-repo/container2:latest', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/kubernetesassignment-428915/kubernetes-assignment-repo/container2:latest']
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=deployment-service.yaml,pvc.yaml
  - --image=us-central1-docker.pkg.dev/kubernetesassignment-428915/kubernetes-assignment-repo/container2
  - --location=us-central1
  - --cluster=kuberneres-assignment-cluster
images:
- 'us-central1-docker.pkg.dev/kubernetesassignment-428915/kubernetes-assignment-repo/container2:latest'
options:
  logging: CLOUD_LOGGING_ONLY
