apiVersion: apps/v1
kind: Deployment
metadata:
  name: container-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container-2
  template:
    metadata:
      labels:
        app: container-2
    spec:
      containers:
      - name: container-2
        image: gcr.io/kubernetesassignment-428818/container-2
        ports:
        - containerPort: 8080
